### ISSUE TITLE
Fantomska greska 

### ISSUE THREAD

**Issue by mirkojvc** [mirkojvc/OrganskoMesto#9]
![screenshot from 2016-11-20 18-50-03](https://cloud.githubusercontent.com/assets/18366380/20464928/74ef9260-af52-11e6-9133-c594dfd2d8a5.png)
Manifestuje se prilikom prelaska sa strane na stranu samo ako je otvoren dev tools znas li sta je u pitanju?

**Comment by djuka038** [comment]
To je neka greška u jquery nije vezano za mene.
